# Site settings
name: evgenii
description: Home of Evgenii
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://evgenii.com" # the base hostname & protocol for your site

author:
  name: Evgenii Neumerzhitckii
  email: sausageskin-at-gmail-com
  google_plus_url: https://plus.google.com/+EvgeniiNeumerzhitckii
  google_plus_page_url: https://www.google.com/+EvgeniiN

# Build settings
markdown: redcarpet

# No syntax highlighter. JavaScript one is used intead.
highlighter: null

# sass:
  # style: :compressed

permalink: /:categories/:title/

sitemap:
  exclude: ["/atom.xml", "/feed.xml", "/feed/index.xml", "/js/script.js", "/js/old_ie.js", "/css/main.scss", "/js/javascript-game-bundle.js",
  "/files/2016/04/harmonic_oscillator/the_complete_code.md",
  "/files/2016/08/card_experiment/index.md",
  "/files/2016/08/card_experiment/the_complete_code.md",
  "/files/2016/09/earth_orbit_simulation/the_complete_code.md",
  "/files/2016/09/carl_in_orbit/index.md",
  "/files/2016/09/ridiculous_strawberry_picking/the_complete_code.md"]
